### ISSUE TITLE
Make sure Django is installed properly for dev environment

### ISSUE THREAD

**Issue by billyc** [psrc/model-dashboard#77]
- Get latest Django
- Get dev system up and running

**Comment by bricegnichols** [comment]
should we be using virtualenv?

**Comment by billyc** [comment]
Found this recipe
http://michal.karzynski.pl/blog/2013/06/09/django-nginx-gunicorn-virtualenv-supervisor/

seems eerily perfectly-suited...

**Comment by billyc** [comment]
Complete. Followed the recipe to the letter; other than a few google-able gotchas, was able to get it up and running on the internal test server.

We now have a real system! Using:
- Postgresql database
- Gunicorn WSGI app server backend
- Nginx webserver front-end
- virtualenv-encapsulated python installation
- Django 1.9

**Comment by Ennazus** [comment]
Sweet!

**Comment by bricegnichols** [comment]
Cool, I will get it running on my PC and update the docs

**Comment by billyc** [comment]
@bricegnichols -- to be clear, you don't need to follow this complex recipe for the dev environment on your desktop; a basic django setup (with its default debug server and a local sqlite db) is fine for development and testing. The recipe is for a solid production-level installation.
